
name: Build and Send Report
on:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '30 5,17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      # - name: Build report

      - name: Send report
        uses: dawidd6/action-send-mail@6d23605227c578d570e5594931720f85a1af55a2 #v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Daily YNAB Report
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECIPIENTS}}
          # Required sender full name (address can be skipped):
          from: YNAB Reporter
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          # body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://report.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: false
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
