name: Build and Send Report
on:
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # - cron:  '30 5,17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send report
        env:
          MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_RECIPIENTS: ${{ secrets.MAIL_RECIPIENTS }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        run: |
          python src/graph.py
